import type { Locale } from "../domain";
import type { Difficulty, ExperienceKind, TransportMode } from "../product/types";
import { msg } from "./catalogs";

export const panUi = {
  en: { tagline: "Better Alpine choices", language: "Interface language", openMenu: "Open menu", alternatives: "Personalised alternatives", noAccount: "No account required", localPlanning: "Planning data stays on this device until you choose to synchronise it.", parser: "Understands EN, IT, DE, FR and SL. Every choice stays editable.", resolving: "Resolving location…", notFound: "Location not found", typePlace: "Type a city or Alpine place", travelImpact: "Changes estimated and routed travel time", impractical: "Used to reject impractical plans", from: "From", to: "To", chooseMatters: "Choose only what matters", unsuitable: "Unsuitable experiences are excluded", catalogue: "Mapped prototype locations", catalogueBody: "curated and open-data locations in the 66-place prototype catalogue", quality: "A better experience, not just a quieter one", qualityBody: "Compatibility, access, duration and specific needs are checked before crowd pressure improves the rank.", showMore: "Show more compatible results", showLess: "Show only the top three", mixed: "Mixed mobility", challenging: "Challenging", short: "1–2 hours", half: "Half day", full: "Full day", multi: "Multiple days", needs: ["Children", "Dog", "Reduced mobility", "Stroller", "No exposed paths", "Indoor alternative", "Low-cost"] },
  it: { tagline: "Scelte alpine migliori", language: "Lingua dell’interfaccia", openMenu: "Apri menu", alternatives: "Alternative personalizzate", noAccount: "Nessun account richiesto", localPlanning: "I dati del piano restano sul dispositivo finché non scegli di sincronizzarli.", parser: "Comprende EN, IT, DE, FR e SL. Ogni scelta resta modificabile.", resolving: "Ricerca della posizione…", notFound: "Posizione non trovata", typePlace: "Scrivi una città o località alpina", travelImpact: "Modifica tempi stimati e calcolati sul percorso", impractical: "Serve a escludere piani impraticabili", from: "Dalle", to: "Alle", chooseMatters: "Scegli solo ciò che conta", unsuitable: "Le esperienze non adatte vengono escluse", catalogue: "Località mappate nel prototipo", catalogueBody: "località curate e open data del catalogo prototipo di 66 luoghi", quality: "Un’esperienza migliore, non soltanto più tranquilla", qualityBody: "Compatibilità, accesso, durata ed esigenze vengono controllati prima che l’affollamento migliori il posizionamento.", showMore: "Mostra altri risultati compatibili", showLess: "Mostra solo i primi tre", mixed: "Mobilità mista", challenging: "Impegnativo", short: "1–2 ore", half: "Mezza giornata", full: "Giornata intera", multi: "Più giorni", needs: ["Bambini", "Cane", "Mobilità ridotta", "Passeggino", "Nessun tratto esposto", "Alternativa al coperto", "Economico"] },
  de: { tagline: "Bessere Entscheidungen in den Alpen", language: "Oberflächensprache", openMenu: "Menü öffnen", alternatives: "Personalisierte Alternativen", noAccount: "Kein Konto erforderlich", localPlanning: "Planungsdaten bleiben auf diesem Gerät, bis du die Synchronisierung wählst.", parser: "Versteht EN, IT, DE, FR und SL. Jede Auswahl bleibt bearbeitbar.", resolving: "Ort wird gesucht…", notFound: "Ort nicht gefunden", typePlace: "Stadt oder Alpenort eingeben", travelImpact: "Ändert geschätzte und geroutete Reisezeiten", impractical: "Unpraktische Pläne werden ausgeschlossen", from: "Von", to: "Bis", chooseMatters: "Nur Wichtiges auswählen", unsuitable: "Ungeeignete Erlebnisse werden ausgeschlossen", catalogue: "Kartierte Prototyp-Orte", catalogueBody: "kuratierte und offene Orte im Prototyp-Katalog mit 66 Einträgen", quality: "Ein besseres Erlebnis, nicht nur ein ruhigeres", qualityBody: "Eignung, Zugang, Dauer und Bedürfnisse werden vor dem Besuchsdruck geprüft.", showMore: "Mehr passende Ergebnisse", showLess: "Nur die besten drei", mixed: "Gemischte Mobilität", challenging: "Anspruchsvoll", short: "1–2 Stunden", half: "Halber Tag", full: "Ganzer Tag", multi: "Mehrere Tage", needs: ["Kinder", "Hund", "Eingeschränkte Mobilität", "Kinderwagen", "Keine ausgesetzten Wege", "Alternative drinnen", "Günstig"] },
  fr: { tagline: "De meilleurs choix alpins", language: "Langue de l’interface", openMenu: "Ouvrir le menu", alternatives: "Alternatives personnalisées", noAccount: "Aucun compte requis", localPlanning: "Les données du parcours restent sur cet appareil jusqu’à votre choix de synchronisation.", parser: "Comprend EN, IT, DE, FR et SL. Chaque choix reste modifiable.", resolving: "Recherche du lieu…", notFound: "Lieu introuvable", typePlace: "Saisissez une ville ou un lieu alpin", travelImpact: "Modifie les temps estimés et calculés", impractical: "Permet d’écarter les parcours irréalistes", from: "De", to: "À", chooseMatters: "Choisissez seulement l’essentiel", unsuitable: "Les expériences inadaptées sont exclues", catalogue: "Lieux cartographiés du prototype", catalogueBody: "lieux éditoriaux et ouverts du catalogue prototype de 66 sites", quality: "Une meilleure expérience, pas seulement plus calme", qualityBody: "Compatibilité, accès, durée et besoins sont vérifiés avant la pression touristique.", showMore: "Afficher plus de résultats compatibles", showLess: "Afficher seulement les trois premiers", mixed: "Mobilité mixte", challenging: "Difficile", short: "1–2 heures", half: "Demi-journée", full: "Journée entière", multi: "Plusieurs jours", needs: ["Enfants", "Chien", "Mobilité réduite", "Poussette", "Sans passages exposés", "Alternative intérieure", "Petit budget"] },
  sl: { tagline: "Boljše izbire v Alpah", language: "Jezik vmesnika", openMenu: "Odpri meni", alternatives: "Prilagojene alternative", noAccount: "Račun ni potreben", localPlanning: "Podatki načrta ostanejo v tej napravi, dokler ne izberete sinhronizacije.", parser: "Razume EN, IT, DE, FR in SL. Vsako izbiro lahko spremenite.", resolving: "Iskanje lokacije…", notFound: "Lokacije ni bilo mogoče najti", typePlace: "Vnesite mesto ali alpski kraj", travelImpact: "Spremeni ocenjen in izračunan čas poti", impractical: "Izloči neizvedljive načrte", from: "Od", to: "Do", chooseMatters: "Izberite le pomembno", unsuitable: "Neustrezna doživetja so izločena", catalogue: "Kartirani kraji prototipa", catalogueBody: "urejeni in odprti kraji v prototipnem katalogu 66 lokacij", quality: "Boljše doživetje, ne le mirnejše", qualityBody: "Ustreznost, dostop, trajanje in potrebe se preverijo pred oceno gneče.", showMore: "Prikaži več ustreznih rezultatov", showLess: "Prikaži le prve tri", mixed: "Mešana mobilnost", challenging: "Zahtevno", short: "1–2 uri", half: "Pol dneva", full: "Ves dan", multi: "Več dni", needs: ["Otroci", "Pes", "Omejena mobilnost", "Otroški voziček", "Brez izpostavljenih poti", "Notranja alternativa", "Nizki stroški"] },
} as const;

export const transportLabel = (locale: Locale, mode: TransportMode) => {
  const key = mode === "walking" ? "data.transport.walking" : mode === "bicycle" ? "data.transport.cycling" : mode === "public" ? "data.transport.public_transport" : mode === "car" ? "data.transport.driving" : null;
  return key ? msg(locale, key) : panUi[locale].mixed;
};

export const kindLabel = (locale: Locale, kind: ExperienceKind) => {
  const keys: Partial<Record<ExperienceKind, string>> = { hiking: "data.interest.hiking", nature: "data.interest.nature", culture: "data.interest.culture", water: "data.interest.water", castle: "data.interest.castles" };
  if (kind === "villages") return locale === "it" ? "Borghi" : locale === "de" ? "Dörfer" : locale === "fr" ? "Villages" : locale === "sl" ? "Vasi" : "Villages";
  if (kind === "family") return locale === "it" ? "Per famiglie" : locale === "de" ? "Familienfreundlich" : locale === "fr" ? "En famille" : locale === "sl" ? "Za družine" : "Family-friendly";
  if (kind === "museum") return locale === "it" ? "Musei" : locale === "de" ? "Museen" : locale === "fr" ? "Musées" : locale === "sl" ? "Muzeji" : "Museums";
  if (kind === "food") return locale === "it" ? "Cibo" : locale === "de" ? "Kulinarik" : locale === "fr" ? "Gastronomie" : locale === "sl" ? "Kulinarika" : "Food";
  if (kind === "accessible") return locale === "it" ? "Accessibile" : locale === "de" ? "Barrierearm" : locale === "fr" ? "Accessible" : locale === "sl" ? "Dostopno" : "Accessible";
  if (kind === "winter") return locale === "it" ? "Inverno" : locale === "de" ? "Winter" : locale === "fr" ? "Hiver" : locale === "sl" ? "Zima" : "Winter";
  return msg(locale, keys[kind] ?? "data.interest.nature");
};

export const difficultyLabel = (locale: Locale, difficulty: Difficulty) => difficulty === "challenging" ? panUi[locale].challenging : msg(locale, difficulty === "easy" ? "data.difficulty.easy" : "data.difficulty.moderate");
