"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, Globe2, HeartHandshake, Linkedin, Mountain, ShieldCheck, Users } from "lucide-react";
import MarketingHeader from "../components/MarketingHeader";
import { team } from "../content";
import { usePersistentLocale } from "../hooks/usePersistentLocale";
import { marketingCopy } from "../i18n/marketing";

const content = {
  en: { eyebrow: "Why GemGo exists", title: "Better choices can redistribute Alpine tourism.", intro: "Search engines and booking platforms reinforce popularity: famous places receive more visibility while comparable nearby destinations and local economies are overlooked. GemGo changes the default choice without restricting where people may travel.", problem: "The problem", problemTitle: "Overtourism is concentrated in space and time", problemBody: "The same Alpine hotspots absorb environmental pressure, queues and local frustration. Nearby communities with comparable natural and cultural value receive fewer visitors and less economic benefit.", solution: "The GemGo approach", solutionTitle: "Recommend, explain and reward a credible alternative", solutionBody: "GemGo considers interests, mobility, available time, weather and estimated crowd pressure. It presents honest trade-offs, verifies completed visits and can connect GemPoints to local benefits once real partnerships are active.", today: "Prototype today", todayBody: "Deterministic ranking, an official 50-place pilot catalogue, open maps, road routing, live weather where available, device-local profiles and clearly labelled demonstration rewards.", future: "After funding and partnerships", futureBody: "Validated crowd prediction, production accounts, territorial data agreements, real partner offers and privacy-preserving aggregated impact reporting.", team: "Meet the team", roles: ["Product Development Lead", "Business Strategy Lead", "Partnerships & Growth Lead"], bios: ["App development, infrastructure, recommendation logic and future AI systems.", "Business development, strategy and financial planning.", "Merchant recruitment, institutional partnerships and go-to-market."], hackathon: "GemGo was created for the European Union Strategy for the Alpine Region AI hackathon in 2026.", award: "The prototype was awarded by a jury of experts and regional representatives.", cta: "Try the prototype" },
  it: { eyebrow: "Perché esiste GemGo", title: "Scelte migliori possono ridistribuire il turismo alpino.", intro: "Motori di ricerca e piattaforme di prenotazione rafforzano la popolarità: i luoghi famosi ottengono più visibilità, mentre destinazioni comparabili ed economie locali vicine restano ignorate. GemGo cambia la scelta predefinita senza limitare la libertà di viaggio.", problem: "Il problema", problemTitle: "L’overtourism si concentra nello spazio e nel tempo", problemBody: "Gli stessi hotspot alpini assorbono pressione ambientale, code e disagio locale. Comunità vicine con valore naturale e culturale comparabile ricevono meno visitatori e benefici economici.", solution: "L’approccio GemGo", solutionTitle: "Consigliare, spiegare e premiare un’alternativa credibile", solutionBody: "GemGo considera interessi, mobilità, tempo disponibile, meteo e affollamento stimato. Mostra compromessi onesti, verifica le visite e potrà collegare i GemPoints a benefici locali quando saranno attive partnership reali.", today: "Prototipo attuale", todayBody: "Ranking deterministico, catalogo pilota ufficiale di 50 luoghi, mappe aperte, routing stradale, meteo live dove disponibile, profili locali e premi dimostrativi chiaramente indicati.", future: "Dopo finanziamento e partnership", futureBody: "Previsione validata dell’affollamento, account di produzione, accordi sui dati territoriali, offerte partner reali e misurazione aggregata rispettosa della privacy.", team: "Conosci il team", roles: ["Responsabile sviluppo prodotto", "Responsabile strategia aziendale", "Responsabile partnership e crescita"], bios: ["Sviluppo app, infrastruttura, logica di raccomandazione e futuri sistemi AI.", "Sviluppo aziendale, strategia e pianificazione finanziaria.", "Reclutamento esercenti, partnership istituzionali e go-to-market."], hackathon: "GemGo è stato creato per l’European Union Strategy for the Alpine Region AI hackathon in 2026.", award: "Il prototipo è stato premiato da una giuria di esperti e rappresentanti regionali.", cta: "Prova il prototipo" },
  de: { eyebrow: "Warum GemGo", title: "Bessere Entscheidungen können den Alpentourismus verteilen.", intro: "Such- und Buchungsplattformen verstärken Bekanntheit. Berühmte Orte erhalten mehr Sichtbarkeit, während vergleichbare Ziele und lokale Wirtschaftsräume übersehen werden. GemGo verändert die Standardwahl, ohne Reisefreiheit einzuschränken.", problem: "Das Problem", problemTitle: "Overtourism konzentriert sich räumlich und zeitlich", problemBody: "Dieselben Hotspots tragen Umweltbelastung, Warteschlangen und lokalen Unmut. Nahe Gemeinden mit vergleichbarem Natur- und Kulturwert erhalten weniger Besuche und Nutzen.", solution: "Der GemGo-Ansatz", solutionTitle: "Eine glaubwürdige Alternative empfehlen, erklären und belohnen", solutionBody: "GemGo berücksichtigt Interessen, Mobilität, Zeit, Wetter und geschätzten Andrang. Es zeigt Kompromisse, bestätigt Besuche und kann GemPoints mit lokalen Vorteilen verbinden, sobald reale Partnerschaften aktiv sind.", today: "Prototyp heute", todayBody: "Deterministisches Ranking, offizieller Pilotkatalog mit 50 Orten, offene Karten, Straßenrouting, Live-Wetter, lokale Profile und gekennzeichnete Demo-Prämien.", future: "Nach Finanzierung und Partnerschaften", futureBody: "Validierte Besucherprognose, Produktivkonten, territoriale Datenvereinbarungen, echte Partnerangebote und datenschutzfreundliche aggregierte Wirkungsmessung.", team: "Das Team", roles: ["Leitung Produktentwicklung", "Leitung Geschäftsstrategie", "Leitung Partnerschaften & Wachstum"], bios: ["App, Infrastruktur, Empfehlungslogik und künftige KI-Systeme.", "Geschäftsentwicklung, Strategie und Finanzplanung.", "Betriebe, Institutionen und Markteinführung."], hackathon: "GemGo entstand für den European Union Strategy for the Alpine Region AI hackathon in 2026.", award: "Der Prototyp wurde von einer Jury aus Fachleuten und regionalen Vertretern ausgezeichnet.", cta: "Prototyp testen" },
  fr: { eyebrow: "Pourquoi GemGo", title: "De meilleurs choix peuvent redistribuer le tourisme alpin.", intro: "Les moteurs de recherche et plateformes de réservation renforcent la popularité : les lieux célèbres gagnent en visibilité, tandis que des destinations comparables et les économies voisines restent ignorées. GemGo modifie le choix par défaut sans limiter la liberté de voyager.", problem: "Le problème", problemTitle: "Le surtourisme se concentre dans l’espace et le temps", problemBody: "Les mêmes sites subissent pression environnementale, files d’attente et mécontentement local. Des communautés proches de valeur comparable reçoivent moins de visiteurs et de bénéfices.", solution: "L’approche GemGo", solutionTitle: "Recommander, expliquer et récompenser une alternative crédible", solutionBody: "GemGo considère intérêts, mobilité, temps, météo et affluence estimée. Il présente les compromis, vérifie les visites et pourra relier les GemPoints à des avantages locaux avec de vrais partenaires.", today: "Prototype actuel", todayBody: "Classement déterministe, catalogue pilote officiel de 50 lieux, cartes ouvertes, itinéraires routiers, météo en direct, profils locaux et récompenses de démonstration signalées.", future: "Après financement et partenariats", futureBody: "Prévision validée, comptes de production, accords de données territoriales, offres réelles et mesure agrégée respectueuse de la vie privée.", team: "L’équipe", roles: ["Responsable développement produit", "Responsable stratégie", "Responsable partenariats et croissance"], bios: ["Application, infrastructure, recommandation et futurs systèmes d’IA.", "Développement, stratégie et planification financière.", "Commerçants, institutions et mise sur le marché."], hackathon: "GemGo a été créé pour le European Union Strategy for the Alpine Region AI hackathon in 2026.", award: "Le prototype a été récompensé par un jury d’experts et de représentants régionaux.", cta: "Essayer le prototype" },
  sl: { eyebrow: "Zakaj GemGo", title: "Boljše izbire lahko prerazporedijo alpski turizem.", intro: "Iskalniki in rezervacijske platforme krepijo priljubljenost: znani kraji dobijo več vidnosti, primerljive destinacije in lokalna gospodarstva pa ostanejo spregledani. GemGo spremeni privzeto izbiro brez omejevanja potovanj.", problem: "Težava", problemTitle: "Čezmerni turizem je zgoščen v prostoru in času", problemBody: "Iste točke nosijo okoljski pritisk, vrste in nezadovoljstvo prebivalcev. Bližnje skupnosti s primerljivo vrednostjo prejmejo manj obiskov in gospodarskih koristi.", solution: "Pristop GemGo", solutionTitle: "Priporočiti, pojasniti in nagraditi verodostojno alternativo", solutionBody: "GemGo upošteva interese, mobilnost, čas, vreme in ocenjeno obremenjenost. Prikaže kompromise, potrdi obiske in bo GemPoints povezal z lokalnimi koristmi, ko bodo aktivna prava partnerstva.", today: "Današnji prototip", todayBody: "Deterministično razvrščanje, uradni pilotni katalog 50 krajev, odprti zemljevidi, cestne poti, vreme v živo, lokalni profili in označene predstavitvene nagrade.", future: "Po financiranju in partnerstvih", futureBody: "Potrjeno napovedovanje obiska, produkcijski računi, podatkovni dogovori, prave ponudbe in zasebnosti prijazno združeno merjenje učinkov.", team: "Ekipa", roles: ["Vodja razvoja izdelka", "Vodja poslovne strategije", "Vodja partnerstev in rasti"], bios: ["Aplikacija, infrastruktura, priporočila in prihodnji sistemi AI.", "Poslovni razvoj, strategija in finančno načrtovanje.", "Ponudniki, ustanove in vstop na trg."], hackathon: "GemGo je bil ustvarjen za European Union Strategy for the Alpine Region AI hackathon in 2026.", award: "Prototip je nagradila žirija strokovnjakov in regionalnih predstavnikov.", cta: "Preizkusi prototip" },
} as const;

const catalogueSummaryCopy = {
  en: "Deterministic ranking, 50 official pilot places plus 16 unique Bavarian Alpify entries, open maps, road routing, live weather where available, device-local profiles and clearly labelled demonstration rewards.",
  it: "Ranking deterministico, 50 luoghi pilota ufficiali più 16 voci uniche bavaresi di Alpify, mappe aperte, routing stradale, meteo live dove disponibile, profili locali e premi dimostrativi chiaramente indicati.",
  de: "Deterministisches Ranking, 50 offizielle Pilotorte plus 16 eindeutige bayerische Alpify-Einträge, offene Karten, Straßenrouting, Live-Wetter, lokale Profile und gekennzeichnete Demo-Prämien.",
  fr: "Classement déterministe, 50 lieux pilotes officiels plus 16 entrées bavaroises Alpify uniques, cartes ouvertes, itinéraires routiers, météo en direct, profils locaux et récompenses de démonstration signalées.",
  sl: "Deterministično razvrščanje, 50 uradnih pilotnih krajev in 16 edinstvenih bavarskih vnosov Alpify, odprti zemljevidi, cestne poti, vreme v živo, lokalni profili in označene predstavitvene nagrade.",
} as const;

export default function AboutPage() {
  const { locale, setLocale } = usePersistentLocale(); const t = { ...content[locale], todayBody: catalogueSummaryCopy[locale] }; const marketing = marketingCopy[locale];
  return <main className="marketing-page standalone-info-page"><MarketingHeader locale={locale} onLocaleChange={setLocale} copy={marketing} /><section className="info-page-hero"><span className="eyebrow"><Globe2 size={15} />{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p></section><section className="about-story-grid"><article><Users /><span>{t.problem}</span><h2>{t.problemTitle}</h2><p>{t.problemBody}</p></article><article><HeartHandshake /><span>{t.solution}</span><h2>{t.solutionTitle}</h2><p>{t.solutionBody}</p></article></section><section className="product-reality-grid info-reality"><article><BadgeCheck /><span>{t.today}</span><p>{t.todayBody}</p></article><article><ShieldCheck /><span>{t.future}</span><p>{t.futureBody}</p></article></section><section className="about-team-page"><div className="section-intro"><span className="eyebrow"><Users size={15} />GemGo</span><h2>{t.team}</h2></div><div className="team-photo-grid">{team.map((person,index) => <article key={person.name}><img src={person.photo} alt={person.name} /><div><h3>{person.name}</h3><strong>{t.roles[index]}</strong><p>{t.bios[index]}</p><a href={person.linkedin} target="_blank" rel="noreferrer" className="team-linkedin"><Linkedin size={16} />LinkedIn</a></div></article>)}</div><div className="hackathon-note"><Mountain /><p><strong>{t.hackathon}</strong><span>{t.award}</span></p></div></section><section className="final-cta-section"><div><h2>{marketing.final.title}</h2><p>{marketing.final.body}</p></div><Link href="/app" className="button button-primary button-large">{t.cta}<ArrowRight /></Link></section></main>;
}
