"use client";

import { Clock3, Database, Download, Globe2, MapPin, ShieldCheck, Trash2, UserRound } from "lucide-react";
import MarketingHeader from "../components/MarketingHeader";
import { usePersistentLocale } from "../hooks/usePersistentLocale";
import { marketingCopy } from "../i18n/marketing";
import { msg } from "../i18n/catalogs";

const privacy = {
  en: { title: "Privacy Policy", intro: "GemGo is designed for European data-protection requirements, including the GDPR principles of lawfulness, transparency, purpose limitation, data minimisation, accuracy, storage limitation and security.", cards: [["Local-first demo","Plans, profile, GemPoints and badge progress are stored in this browser for the current prototype."],["Location on request","Precise location is requested only for routing or visit verification. The prototype does not keep a continuous movement history."],["No production account yet","The current email profile is device-local. It is not transmitted to a GemGo server or synchronised across devices."],["Future services","Before analytics, cloud accounts, photo moderation or real rewards launch, GemGo will publish purposes, legal bases, retention periods and processor details."]], rights: "Your controls", rightsBody: "You can export the current device-local GemGo data or delete it from this browser. Deletion cannot be undone.", export: "Export local data", remove: "Delete local data", removed: "Local GemGo data deleted.", back: "Back to GemGo" },
  it: { title: "Informativa sulla privacy", intro: "GemGo è progettato per i requisiti europei di protezione dei dati, compresi i principi GDPR di liceità, trasparenza, limitazione delle finalità, minimizzazione, accuratezza, limitazione della conservazione e sicurezza.", cards: [["Demo local-first","Piani, profilo, GemPoints e progresso badge sono salvati in questo browser nel prototipo attuale."],["Posizione su richiesta","La posizione precisa viene richiesta solo per routing o verifica della visita. Il prototipo non conserva uno storico continuo degli spostamenti."],["Nessun account di produzione","Il profilo email attuale è locale al dispositivo: non viene inviato a un server GemGo né sincronizzato."],["Servizi futuri","Prima di analytics, account cloud, moderazione foto o premi reali, GemGo pubblicherà finalità, basi giuridiche, tempi di conservazione e responsabili."]], rights: "I tuoi controlli", rightsBody: "Puoi esportare i dati GemGo locali o eliminarli da questo browser. L’eliminazione non può essere annullata.", export: "Esporta dati locali", remove: "Elimina dati locali", removed: "Dati GemGo locali eliminati.", back: "Torna a GemGo" },
  de: { title: "Datenschutzerklärung", intro: "GemGo ist für europäische Datenschutzanforderungen konzipiert, einschließlich der DSGVO-Grundsätze Rechtmäßigkeit, Transparenz, Zweckbindung, Datenminimierung, Richtigkeit, Speicherbegrenzung und Sicherheit.", cards: [["Lokale Demo","Pläne, Profil, GemPoints und Abzeichen werden im aktuellen Prototyp in diesem Browser gespeichert."],["Standort auf Anfrage","Der genaue Standort wird nur für Routen oder Besuchsbestätigung angefragt. Es gibt keinen kontinuierlichen Bewegungsverlauf."],["Noch kein Produktivkonto","Das E-Mail-Profil bleibt auf dem Gerät und wird nicht an GemGo übertragen oder synchronisiert."],["Künftige Dienste","Vor Analytics, Cloud-Konten, Fotomoderation oder echten Prämien veröffentlicht GemGo Zwecke, Rechtsgrundlagen, Fristen und Auftragsverarbeiter."]], rights: "Deine Kontrollen", rightsBody: "Lokale GemGo-Daten können exportiert oder aus diesem Browser gelöscht werden.", export: "Lokale Daten exportieren", remove: "Lokale Daten löschen", removed: "Lokale GemGo-Daten gelöscht.", back: "Zurück zu GemGo" },
  fr: { title: "Politique de confidentialité", intro: "GemGo est conçu selon les exigences européennes de protection des données et les principes du RGPD : licéité, transparence, limitation des finalités, minimisation, exactitude, conservation limitée et sécurité.", cards: [["Démo locale","Plans, profil, GemPoints et badges sont enregistrés dans ce navigateur pour le prototype."],["Localisation sur demande","La position précise est demandée uniquement pour l’itinéraire ou la vérification. Aucun historique continu n’est conservé."],["Pas encore de compte de production","Le profil e-mail reste sur l’appareil et n’est ni envoyé ni synchronisé."],["Services futurs","Avant l’analytique, les comptes cloud, la modération photo ou les récompenses réelles, GemGo publiera finalités, bases légales, durées et sous-traitants."]], rights: "Vos contrôles", rightsBody: "Vous pouvez exporter ou supprimer les données GemGo locales de ce navigateur.", export: "Exporter les données locales", remove: "Supprimer les données locales", removed: "Données GemGo locales supprimées.", back: "Retour à GemGo" },
  sl: { title: "Pravilnik o zasebnosti", intro: "GemGo je zasnovan skladno z evropskimi zahtevami varstva podatkov in načeli GDPR: zakonitost, preglednost, omejitev namena, najmanjši obseg podatkov, točnost, omejitev hrambe in varnost.", cards: [["Lokalna predstavitev","Načrti, profil, GemPoints in značke so v prototipu shranjeni v tem brskalniku."],["Lokacija na zahtevo","Natančna lokacija se zahteva samo za pot ali potrditev obiska. Stalna zgodovina gibanja se ne hrani."],["Brez produkcijskega računa","E-poštni profil ostane v napravi in se ne pošilja ali sinhronizira."],["Prihodnje storitve","Pred analitiko, računi v oblaku, moderiranjem fotografij ali pravimi nagradami bo GemGo objavil namene, pravne podlage, roke in obdelovalce."]], rights: "Vaše možnosti", rightsBody: "Lokalne podatke GemGo lahko izvozite ali izbrišete iz tega brskalnika.", export: "Izvozi lokalne podatke", remove: "Izbriši lokalne podatke", removed: "Lokalni podatki GemGo so izbrisani.", back: "Nazaj na GemGo" },
} as const;

export default function PrivacyPage() {
  const { locale,setLocale } = usePersistentLocale(); const t = privacy[locale]; const copy = marketingCopy[locale];
  const cards = [...t.cards, [msg(locale, "privacy.servicesTitle"), msg(locale, "privacy.servicesBody")], [msg(locale, "privacy.retentionTitle"), msg(locale, "privacy.retentionBody")]] as const;
  const exportData = () => { const data: Record<string,string|null> = {}; for(let i=0;i<localStorage.length;i+=1){ const key=localStorage.key(i); if(key?.startsWith("gemgo")) data[key]=localStorage.getItem(key); } const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"})); const a=document.createElement("a"); a.href=url; a.download="gemgo-local-data.json"; a.click(); URL.revokeObjectURL(url); };
  const remove = () => { if(!confirm(t.remove+"?")) return; Object.keys(localStorage).filter((key)=>key.startsWith("gemgo")).forEach((key)=>localStorage.removeItem(key)); alert(t.removed); };
  const icons=[Database,MapPin,UserRound,ShieldCheck,Globe2,Clock3];
  return <main className="marketing-page standalone-info-page"><MarketingHeader locale={locale} onLocaleChange={setLocale} copy={copy}/><section className="info-page-hero privacy-title"><span className="eyebrow"><ShieldCheck size={15}/>GDPR</span><h1>{t.title}</h1><p>{t.intro}</p></section><section className="privacy-policy-grid">{cards.map(([title,body],index)=>{const Icon=icons[index];return <article key={title}><Icon/><h2>{title}</h2><p>{body}</p></article>;})}</section><section className="privacy-control-card"><div><h2>{t.rights}</h2><p>{t.rightsBody}</p></div><div><button className="button button-secondary" onClick={exportData}><Download/>{t.export}</button><button className="button privacy-delete-button" onClick={remove}><Trash2/>{t.remove}</button></div></section></main>;
}
