import type { Season } from "./types";

export type DestinationEditorial = {
  name?: string;
  caption: string;
  sourceUrl: string;
  sourceLabel: string;
  seasons: Season[];
  peakSeasons: Season[];
  operationalNote?: string;
};

const all: Season[] = ["spring", "summer", "autumn", "winter"];
const green: Season[] = ["spring", "summer", "autumn"];
const alpine: Season[] = ["summer", "autumn"];
const warm: Season[] = ["summer"];
const winter: Season[] = ["winter"];

// Short, factual editorial copy replaces the prototype's generated marketing
// phrases. Each entry points to a public authority, destination-management
// organisation or site operator used for the editorial check.
export const catalogueEditorial: Record<string, DestinationEditorial> = {
  bav_001: { caption: "Historic Mittenwald combines Lüftlmalerei-painted façades, violin-making heritage and walks below the Karwendel range.", sourceUrl: "https://www.alpenwelt-karwendel.de/en/a-historical-tour-through-mittenwald", sourceLabel: "Alpenwelt Karwendel", seasons: all, peakSeasons: ["summer", "winter"] },
  bav_002: { caption: "Staffelsee is a lake near Murnau with islands, bathing access, boat trips and walking or cycling routes.", sourceUrl: "https://www.dasblaueland.de/en/seehausen", sourceLabel: "Das Blaue Land tourism", seasons: green, peakSeasons: warm },
  bav_003: { caption: "Burghausen’s ridge-top fortress extends for more than a kilometre and contains several courtyards and museum spaces.", sourceUrl: "https://www.burg-burghausen.de/englisch/castle/bedeut.htm", sourceLabel: "Bavarian Palace Department", seasons: all, peakSeasons: ["spring", "summer", "autumn"] },
  bav_004: { caption: "Bad Hindelang is a mountain municipality with hiking routes, nature experiences and winter-sport areas in the Allgäu Alps.", sourceUrl: "https://www.germany.travel/en/experience-enjoy/bad-hindelang.html", sourceLabel: "German National Tourist Board", seasons: all, peakSeasons: ["summer", "winter"] },
  bav_005: { caption: "Benediktbeuern pairs its historic monastery complex with paths into the Loisach-Kochelsee moorland.", sourceUrl: "https://www.kloster-benediktbeuern.de/", sourceLabel: "Benediktbeuern Monastery", seasons: all, peakSeasons: green },
  bav_006: { caption: "Waginger See offers designated bathing areas, lakeside leisure and cycling routes in the Chiemgau foothills.", sourceUrl: "https://www.chiemsee-chiemgau.info/waginger-see", sourceLabel: "Chiemgau tourism", seasons: green, peakSeasons: warm },
  bav_007: { caption: "Kochel am See combines lake access with the Franz Marc Museum and routes toward the surrounding mountains.", sourceUrl: "https://bavaria.travel/listicles/lakes-and-rivers/", sourceLabel: "Bavaria Travel", seasons: all, peakSeasons: ["summer", "autumn"] },
  bav_008: { caption: "Marked routes around Garmisch-Partenkirchen provide walking options beyond the Partnach Gorge itself.", sourceUrl: "https://www.gapa-tourismus.de/en/partnach-gorge", sourceLabel: "Garmisch-Partenkirchen tourism", seasons: green, peakSeasons: ["spring", "autumn"], operationalNote: "Check the official gorge and trail status before travelling; closures can affect connected routes." },
  bav_009: { caption: "Reit im Winkl has summer hiking and cycling routes plus a substantial cross-country ski network in winter.", sourceUrl: "https://www.reitimwinkl.de/en", sourceLabel: "Reit im Winkl tourism", seasons: all, peakSeasons: ["summer", "winter"] },
  bav_010: { caption: "Walchensee supports sailing, wind sports, diving and shore-to-mountain excursions in a steep Alpine setting.", sourceUrl: "https://bavaria.travel/listicles/lakes-and-rivers/", sourceLabel: "Bavaria Travel", seasons: green, peakSeasons: warm },
  bav_011: { caption: "Sylvensteinsee is a reservoir on the upper Isar with turquoise water, shore viewpoints and walking or cycling routes.", sourceUrl: "https://bavaria.travel/listicles/lakes-and-rivers/", sourceLabel: "Bavaria Travel", seasons: green, peakSeasons: ["summer", "autumn"] },
  bav_012: { caption: "Andechs is a Benedictine pilgrimage monastery with a church, brewery tradition and views from the Holy Mountain.", sourceUrl: "https://www.andechs.de/en/", sourceLabel: "Andechs Monastery", seasons: all, peakSeasons: green },
  bav_013: { caption: "Jachenau is a broad Alpine valley with working farms and signed walking and cycling routes beneath the Benediktenwand.", sourceUrl: "https://www.jachenau.de/", sourceLabel: "Jachenau municipality", seasons: green, peakSeasons: ["summer", "autumn"] },
  bav_014: { caption: "The Osterseen are a protected chain of glacial lakes; visitors should use marked paths and designated bathing areas.", sourceUrl: "https://www.lra-wm.bayern.de/buergerservice/umwelt/naturschutz/schutzgebiete/osterseen/", sourceLabel: "Weilheim-Schongau district", seasons: green, peakSeasons: warm, operationalNote: "This is a nature reserve: stay on permitted routes and use only designated bathing access." },
  bav_015: { caption: "Oberammergau is known for its Passion Play, woodcarving tradition and Lüftlmalerei-painted buildings.", sourceUrl: "https://www.ammergauer-alpen.de/en/oberammergau", sourceLabel: "Ammergau Alps tourism", seasons: all, peakSeasons: ["summer", "winter"] },
  bav_016: { caption: "Auerberg’s summit area combines Alpine views, the church of St George and traces of Roman-era settlement.", sourceUrl: "https://www.allgaeu.de/sehenswuerdigkeiten/auerberg", sourceLabel: "Allgäu tourism", seasons: green, peakSeasons: ["summer", "autumn"] },
  bav_017: { caption: "Hoher Peißenberg has a panoramic summit and a meteorological observatory with measurements dating from 1781.", sourceUrl: "https://www.dwd.de/EN/research/observing_atmosphere/composition_atmosphere/hohenpeissenberg/hohenpeissenberg_node.html", sourceLabel: "German Weather Service", seasons: all, peakSeasons: ["spring", "summer", "autumn"] },
  bav_018: { caption: "Schliersee is a lakeside market town with shore walks, boat connections and access toward Spitzingsee.", sourceUrl: "https://www.schliersee.de/en/", sourceLabel: "Schliersee tourism", seasons: all, peakSeasons: ["summer", "winter"] },
  bav_019: { caption: "The upper Isar near Isarhorn is a dynamic river landscape best explored on designated walking and cycling routes.", sourceUrl: "https://www.alpenwelt-karwendel.de/en/lakes-waters-bavaria", sourceLabel: "Alpenwelt Karwendel", seasons: green, peakSeasons: ["spring", "autumn"], operationalNote: "Respect protected river habitats and any local access restrictions." },
  bav_020: { caption: "At 1,277 metres, Falkenstein is Germany’s highest castle ruin; a viewing platform recalls Ludwig II’s unrealised castle plans.", sourceUrl: "https://www.pfronten.de/familie/burgen-schloesser/burgruine-falkenstein/", sourceLabel: "Pfronten tourism", seasons: green, peakSeasons: ["summer", "autumn"], operationalNote: "The final approach is on foot; check trail, road and winter conditions before visiting." },
  bav_021: { caption: "Großer Alpsee near Immenstadt is a natural lake used for swimming, sailing and routes through the Alpsee-Grünten area.", sourceUrl: "https://www.alpsee-gruenten.de/", sourceLabel: "Alpsee-Grünten tourism", seasons: green, peakSeasons: warm },
  bav_022: { caption: "Hausham’s Nordic routes form part of the Schliersee valley cross-country network and depend on current snow conditions.", sourceUrl: "https://www.schliersee.de/en/winter/cross-country-skiing/", sourceLabel: "Schliersee tourism", seasons: winter, peakSeasons: winter, operationalNote: "Use only when the local trail report confirms sufficient snow and open tracks." },
  bav_023: { caption: "Miesbach is a historic market town with a walkable centre, regional food shops and Upper Bavarian craft traditions.", sourceUrl: "https://www.miesbach-tourismus.de/", sourceLabel: "Miesbach tourism", seasons: all, peakSeasons: ["spring", "autumn", "winter"] },
  bav_024: { caption: "Lautersee above Mittenwald has a signed circular walk, bathing access and views toward the Wetterstein mountains.", sourceUrl: "https://www.alpenwelt-karwendel.de/en/lakes-waters-bavaria", sourceLabel: "Alpenwelt Karwendel", seasons: green, peakSeasons: warm },
  bav_025: { caption: "Ettal is a Benedictine monastery founded in 1330, centred on a baroque basilica and rococo sacristy.", sourceUrl: "https://www.ammergauer-alpen.de/en/ettal", sourceLabel: "Ammergau Alps tourism", seasons: all, peakSeasons: green },

  vda_001: { caption: "Cogne is a gateway to Gran Paradiso National Park, with valley walks, mountain routes and seasonal shuttle connections.", sourceUrl: "https://www.visitcogne.it/en/", sourceLabel: "Cogne tourism", seasons: all, peakSeasons: ["summer", "winter"] },
  vda_002: { caption: "Chamois is a car-free mountain village reached by cable car from Buisson or by walking and cycling routes.", sourceUrl: "https://www.lovevda.it/en/database/3/tourist-resorts/aosta-valley/chamois/409", sourceLabel: "Aosta Valley tourism", seasons: all, peakSeasons: ["summer", "winter"] },
  vda_003: { caption: "Lago Blu is a small lake near Breuil-Cervinia known for reflections of the Matterhorn and short surrounding walks.", sourceUrl: "https://www.italia.it/en/aosta-valley/cervinia/lago-blu-cervinia", sourceLabel: "Italia.it", seasons: green, peakSeasons: ["summer", "autumn"] },
  vda_004: { name: "Fénis Castle", caption: "Fénis Castle is a medieval fortified residence with towers, internal courtyards, furnished rooms and wall paintings.", sourceUrl: "https://www.italia.it/en/aosta-valley/fenis-castle", sourceLabel: "Italia.it", seasons: all, peakSeasons: green },
  vda_005: { caption: "Valpelline combines a working Fontina visitor centre with village routes and access into the upper valley landscape.", sourceUrl: "https://www.fontina-valledaosta.it/en-gb/the-cooperative/visitors-centre", sourceLabel: "Fontina producers’ cooperative", seasons: all, peakSeasons: ["summer", "autumn"] },
  vda_006: { caption: "Bard pairs a medieval village with the restored Fort of Bard, whose buildings house museums and temporary exhibitions.", sourceUrl: "https://www.fortedibard.it/en/", sourceLabel: "Fort of Bard", seasons: all, peakSeasons: green },
  vda_007: { caption: "Rhêmes-Notre-Dame lies in Gran Paradiso National Park, with conifer woods, alpine meadows and wildlife-viewing routes.", sourceUrl: "https://www.pngp.it/en/visit-park/valleys-and-municipalities/rh%C3%AAmes-valley", sourceLabel: "Gran Paradiso National Park", seasons: all, peakSeasons: ["summer", "winter"] },
  vda_008: { caption: "Introd combines a rural village setting with the Parc Animalier and nearby castle heritage at the entrance to Gran Paradiso valleys.", sourceUrl: "https://www.italia.it/en/aosta-valley/aosta/parc-animalier-d-introd", sourceLabel: "Italia.it", seasons: all, peakSeasons: green },
  vda_009: { caption: "Ollomont offers mountain routes and guided interpretation of the Valpelline area’s historic copper mines.", sourceUrl: "https://www.miniereollomontvalpelline.it/en/visits/", sourceLabel: "Ollomont-Valpelline mines", seasons: green, peakSeasons: ["summer", "autumn"], operationalNote: "Mine visits and high routes require current opening, booking and weather checks." },
  vda_010: { caption: "Torgnon is a sunny plateau village with hiking and cycling in warmer months and ski or Nordic routes in winter.", sourceUrl: "https://www.italia.it/en/aosta-valley/torgnon", sourceLabel: "Italia.it", seasons: all, peakSeasons: ["summer", "winter"] },
  vda_011: { caption: "Gressoney-Saint-Jean combines Walser heritage with Castel Savoia and routes beneath the Monte Rosa massif.", sourceUrl: "https://valledaostaheritage.com/en/castel-savoia/", sourceLabel: "Valle d’Aosta Heritage", seasons: all, peakSeasons: ["summer", "winter"] },
  vda_012: { caption: "Arvier is set among terraced vineyards associated with the Enfer d’Arvier wine and routes through the central valley.", sourceUrl: "https://www.italia.it/en/aosta-valley/arvier", sourceLabel: "Italia.it", seasons: green, peakSeasons: ["summer", "autumn"] },
  vda_013: { caption: "Pont d’Aël is a Roman aqueduct bridge with two levels, including a walkable internal service gallery.", sourceUrl: "https://valledaostaheritage.com/en/ponte-acquedotto-di-pont-dael/", sourceLabel: "Valle d’Aosta Heritage", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },
  vda_014: { caption: "Fontainemore is a lower Lys Valley village and an access point for trails in the Mont Mars Nature Reserve.", sourceUrl: "https://www.vivavda.it/en/natural-areas/mont-mars-nature-reserve", sourceLabel: "VIVA Valle d’Aosta", seasons: green, peakSeasons: ["summer", "autumn"] },
  vda_015: { caption: "Aymavilles Castle has four cylindrical corner towers and an exhibition route through its architecture and collections.", sourceUrl: "https://valledaostaheritage.com/en/chateau-daymavilles/", sourceLabel: "Valle d’Aosta Heritage", seasons: all, peakSeasons: green },
  vda_016: { caption: "Brusson combines the Ayas Valley village and lake with guided visits to the former Chamousira gold mine.", sourceUrl: "https://visitmonterosa.com/en/experiences/miniera-doro-di-chamousira-18941", sourceLabel: "Visit Monterosa", seasons: all, peakSeasons: ["summer", "winter"], operationalNote: "Mine access follows published tour dates; verify opening before departure." },
  vda_017: { caption: "Verrès is centred on a compact fourteenth-century fortress and a historic village that hosts a winter carnival.", sourceUrl: "https://valledaostaheritage.com/en/chateau-de-verres/", sourceLabel: "Valle d’Aosta Heritage", seasons: all, peakSeasons: ["spring", "summer", "winter"] },
  vda_018: { caption: "La Salle is a Mont Blanc-facing wine village with terraced vineyards and the Cave Mont Blanc cooperative nearby.", sourceUrl: "https://www.lasallemontblanc.com/en/tour-item/cave-mont-blanc/", sourceLabel: "La Salle Mont Blanc tourism", seasons: all, peakSeasons: ["summer", "autumn"] },
  vda_019: { caption: "Lillianes is a lower Lys Valley village built along the river, with a historic stone bridge and access to hillside paths.", sourceUrl: "https://www.lovevda.it/en/database/3/tourist-resorts/aosta-valley/lillianes/410", sourceLabel: "Aosta Valley tourism", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },
  vda_020: { caption: "Chambave’s terraced vineyards are associated with Muscat de Chambave and other Valle d’Aosta DOC wines.", sourceUrl: "https://www.vival.it/en/the-wines/moscato-bianco/chambave-muscat/", sourceLabel: "VIVAL winegrowers’ association", seasons: green, peakSeasons: ["summer", "autumn"] },
  vda_021: { caption: "Perloz connects the Resistance Museum with Chemp, a small settlement used as an open-air art setting.", sourceUrl: "https://www.fortedibard.it/en/nearby-fort-of-bard/perloz/", sourceLabel: "Fort of Bard", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },
  vda_022: { caption: "The MegaMuseo at Saint-Martin-de-Corléans presents a megalithic archaeological area with stelae, burials and ritual features.", sourceUrl: "https://valledaostaheritage.com/en/megamuseo/", sourceLabel: "Valle d’Aosta Heritage", seasons: all, peakSeasons: all },
  vda_023: { caption: "The Little Saint Bernard Pass preserves cross-border archaeology and hospice heritage at 2,188 metres.", sourceUrl: "https://www.psbernard.com/en/le-col-a-travers-les-ages/", sourceLabel: "Little Saint Bernard heritage network", seasons: alpine, peakSeasons: warm, operationalNote: "The pass road is seasonal; verify the official reopening and weather before travel." },
  vda_024: { caption: "Châtillon provides access to Ussel Castle and to Gamba Castle’s modern and contemporary art collection.", sourceUrl: "https://www.castellogamba.vda.it/en/gamba-castle", sourceLabel: "Gamba Castle", seasons: all, peakSeasons: green },
  vda_025: { caption: "Machaby Sanctuary stands in chestnut woodland above Arnad and contains votive offerings and a seventeenth-century altar.", sourceUrl: "https://www.inalto.org/en/points-of-interest/sanctuary-of-machaby", sourceLabel: "InAlto local heritage guide", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },

  "alpify-weisensee": { name: "Weißensee", caption: "Weißensee near Füssen has a gently sloping bathing area, a shore circuit and views toward the Allgäu Alps.", sourceUrl: "https://www.fuessen.de/en/fuessen-weissensee/", sourceLabel: "Füssen tourism", seasons: green, peakSeasons: warm },
  "alpify-forgensee": { name: "Forggensee", caption: "Forggensee is a seasonal reservoir used for boat trips, sailing and cycling with views toward the royal castles.", sourceUrl: "https://www.fuessen.de/en/healthy-nature/", sourceLabel: "Füssen tourism", seasons: ["spring", "summer", "autumn"], peakSeasons: warm, operationalNote: "Water level and boat operations are seasonal; the reservoir is drawn down in winter." },
  "alpify-faulensee": { caption: "Faulensee above Rieden is a small moor lake framed by woods and meadows, reached on local walking and cycling routes.", sourceUrl: "https://www.suedliches-allgaeu.de/region-gastgeber/die-fuenf-gemeinden/rieden-am-forggensee/faulensee", sourceLabel: "Südliches Allgäu tourism", seasons: green, peakSeasons: warm },
  "alpify-gaisalpsee": { caption: "Gaisalpsee is a mountain lake above Reichenbach reached on a hiking route with sustained ascent and Alpine terrain.", sourceUrl: "https://www.oberstdorf.de/alpininfo/tourensuche/gaisalpsee.html", sourceLabel: "Oberstdorf tourism", seasons: alpine, peakSeasons: warm, operationalNote: "Mountain conditions, footwear and route status must be checked before departure." },
  "alpify-buchenberg": { caption: "Buchenberg is an Allgäu viewpoint area with walking routes and broad views across the Alpine foothills.", sourceUrl: "https://www.allgaeu.de/orte/buchenberg", sourceLabel: "Allgäu tourism", seasons: all, peakSeasons: ["summer", "autumn", "winter"] },
  "alpify-tegelberg": { caption: "Tegelberg is a mountain excursion above Schwangau, reached by cable car or hiking routes near the royal castles.", sourceUrl: "https://www.tegelbergbahn.de/en/", sourceLabel: "Tegelberg cableway", seasons: all, peakSeasons: ["summer", "winter"], operationalNote: "Check cableway operations, trail status and mountain weather." },
  "alpify-castle-hohenschwangau": { caption: "Hohenschwangau was the royal family’s nineteenth-century summer residence and can be visited on timed tours.", sourceUrl: "https://www.hohenschwangau.de/en/royal-castles/hohenschwangau-castle", sourceLabel: "Hohenschwangau official ticket centre", seasons: all, peakSeasons: ["spring", "summer", "autumn"] },
  "alpify-breitachklamm": { caption: "Breitachklamm is a managed gorge route with paths, bridges and seasonal opening conditions.", sourceUrl: "https://www.breitachklamm.com/en/", sourceLabel: "Breitachklamm operator", seasons: ["spring", "summer", "autumn", "winter"], peakSeasons: ["summer", "winter"], operationalNote: "Entry depends on the official opening and safety report." },
  "alpify-castle-neuschwanstein": { caption: "Neuschwanstein is Ludwig II’s nineteenth-century palace and a major timed-entry visitor destination above Hohenschwangau.", sourceUrl: "https://www.neuschwanstein.de/englisch/tourist/index.htm", sourceLabel: "Bavarian Palace Department", seasons: all, peakSeasons: ["spring", "summer", "autumn"] },
  "alpify-nesselwang-waterfall-trail": { caption: "Nesselwang’s waterfall route follows the wooded Alpspitz area past cascades on a signed hiking circuit.", sourceUrl: "https://www.nesselwang.de/wasserfallweg.html", sourceLabel: "Nesselwang tourism", seasons: green, peakSeasons: ["spring", "summer"] },
  "alpify-starzlachklamm": { caption: "Starzlachklamm is a managed gorge trail near Sonthofen with rock passages, bridges and waterfalls.", sourceUrl: "https://www.starzlachklamm.de/", sourceLabel: "Starzlachklamm operator", seasons: green, peakSeasons: ["spring", "summer"], operationalNote: "Use only during official opening; gorge conditions can change quickly." },
  "alpify-gruenten": { name: "Grünten", caption: "Grünten is a prominent Allgäu mountain with several hiking approaches and viewpoints over the Iller valley.", sourceUrl: "https://www.alpsee-gruenten.de/berge/gruenten", sourceLabel: "Alpsee-Grünten tourism", seasons: green, peakSeasons: ["summer", "autumn"], operationalNote: "Choose a route suited to current mountain and weather conditions." },
  "alpify-castle-ruin-hapfen": { name: "Hopfen Castle Ruin", caption: "Hopfen Castle Ruin stands above Hopfensee and can be combined with a short uphill walk and lake panorama.", sourceUrl: "https://www.fuessen.de/en/culture/castles-museums/castle-region-allgaeu/", sourceLabel: "Füssen tourism", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },
  "alpify-ruin-att-trauchburg": { name: "Alt-Trauchburg Ruin", caption: "Alt-Trauchburg is a medieval castle ruin above Weitnau reached by an uphill walking route.", sourceUrl: "https://www.allgaeu.de/sehenswuerdigkeiten/burgruine-alttrauchburg", sourceLabel: "Allgäu tourism", seasons: green, peakSeasons: ["summer", "autumn"] },
  "alpify-eisenberg-hohenfreyberg": { name: "Eisenberg and Hohenfreyberg Castle Ruins", caption: "Eisenberg and Hohenfreyberg are neighbouring hilltop castle ruins connected by a short walking route.", sourceUrl: "https://www.burgenregion.de/burgen/burgen-eisenberg-hohenfreyberg/", sourceLabel: "Allgäu-Außerfern castle region", seasons: green, peakSeasons: ["spring", "summer", "autumn"] },
  "alpify-buchenegger-waterfalls": { name: "Buchenegger Waterfalls", caption: "The Buchenegger waterfalls are reached on forest paths; water level and slippery terrain require current-condition checks.", sourceUrl: "https://www.oberstaufen.de/natur/buchenegger-wasserfaelle", sourceLabel: "Oberstaufen tourism", seasons: green, peakSeasons: ["spring", "summer"], operationalNote: "Swimming and jumping can be dangerous; follow current local safety guidance." },
};

export const seasonForDate = (dateValue?: string): Season => {
  const date = dateValue ? new Date(dateValue) : new Date();
  const safeDate = Number.isNaN(date.getTime()) ? new Date() : date;
  const month = safeDate.getUTCMonth() + 1;
  if (month === 12 || month <= 2) return "winter";
  if (month <= 5) return "spring";
  if (month <= 8) return "summer";
  return "autumn";
};
