import type { Experience, SearchPreferences } from "./types";

export const defaultPreferences: SearchPreferences = {
  prompt:
    "I’m staying near Aosta, I have half a day and I’d like an easy nature experience without large crowds.",
  origin: "Aosta",
  maxTravelMinutes: 45,
  transport: "car",
  availableTime: "half",
  availableFrom: "14:00",
  availableTo: "18:00",
  kinds: ["nature", "villages"],
  difficulty: "easy",
  needs: [],
};

export const experiences: Experience[] = [
  {
    id: "valpelline-river-villages",
    name: "Valpelline river villages",
    promise: "Quiet river villages and an easy afternoon walk",
    region: "Valle d’Aosta",
    country: "Italy",
    kind: ["nature", "villages", "food"],
    difficulty: "easy",
    latitude: 45.826,
    longitude: 7.325,
    travel: { walking: null, bicycle: 76, public: 42, car: 28, mixed: 39 },
    durationMinutes: 180,
    crowd: "low",
    crowdWindow: "15:00–18:00",
    confidence: "Medium",
    updated: "30 minutes ago",
    validation: "Locally reviewed",
    imageTone: "valley",
    summary:
      "A relaxed riverside route linking small villages, stone bridges and an optional local tasting without the pressure of the main tourism corridor.",
    reasons: [
      "Matches your half-day window",
      "Suitable for light rain",
      "Quieter than your original destination",
    ],
    tradeoffs: ["20 minutes longer to reach than the nearest hotspot", "Limited evening public transport"],
    comparison: {
      original: "Central Aosta and Pila",
      reachDifference: "+20 minutes travel",
      advantages: ["Lower expected crowd", "Easier parking", "Similar easy landscape experience"],
    },
    itinerary: [
      { time: "14:30", label: "Leave from Aosta" },
      { time: "15:00", label: "Arrive and begin the riverside route" },
      { time: "16:20", label: "Visit the village centre" },
      { time: "16:45", label: "Optional local café stop" },
      { time: "17:30", label: "Return" },
    ],
    mobility: [
      "28 minutes by car",
      "Public parking 300 metres from the route",
      "42 minutes by public transport with one change",
      "Last return bus shown before departure",
    ],
    localBenefit:
      "Visiting this valley supports businesses outside the region’s main tourism corridor.",
    partner: "A participating café is located near the end of the route.",
    safety: ["Light rain possible after 17:00", "Easy surfaced and riverside paths", "No known seasonal closure"],
    points: 60,
    crowdByHour: [
      { time: "10:00", level: "moderate" },
      { time: "12:00", level: "high" },
      { time: "15:00", level: "low" },
      { time: "17:00", level: "low" },
    ],
  },
  {
    id: "weissensee-lakeside-loop",
    name: "Weißensee lakeside loop",
    promise: "A calm lake circuit with mountain views and easy access",
    region: "Allgäu",
    country: "Germany",
    kind: ["nature", "water", "family"],
    difficulty: "easy",
    latitude: 47.5755,
    longitude: 10.6243,
    travel: { walking: null, bicycle: 34, public: 31, car: 18, mixed: 27 },
    durationMinutes: 120,
    crowd: "low",
    crowdWindow: "14:30–17:30",
    confidence: "High",
    updated: "18 minutes ago",
    validation: "Verified Gem",
    imageTone: "lake",
    summary:
      "A mostly level walk beside Weißensee with picnic points, a short village section and reliable public-transport access from Füssen.",
    reasons: ["Easy terrain", "Works without a car", "Lower pressure than the castle corridor"],
    tradeoffs: ["Fewer indoor options in poor weather", "Limited food service outside the village"],
    comparison: {
      original: "Neuschwanstein castle corridor",
      reachDifference: "−8 minutes travel",
      advantages: ["Lower expected crowd", "Simpler access", "More flexible visit duration"],
    },
    itinerary: [
      { time: "14:10", label: "Leave Füssen by local bus" },
      { time: "14:35", label: "Start the lakeside loop" },
      { time: "15:25", label: "Picnic and viewpoint stop" },
      { time: "16:10", label: "Village section" },
      { time: "16:40", label: "Return connection" },
    ],
    mobility: ["31 minutes by public transport", "Short walk from the bus stop", "Accessible parking near the eastern shore"],
    localBenefit: "The route distributes visits away from the castle corridor and toward local lakeside services.",
    partner: "A family-run bakery participates in the pilot reward concept.",
    safety: ["Flat route", "Shaded sections can remain wet", "Swimming conditions are not verified by GemGo"],
    points: 55,
    crowdByHour: [
      { time: "10:00", level: "moderate" },
      { time: "12:00", level: "moderate" },
      { time: "15:00", level: "low" },
      { time: "17:00", level: "low" },
    ],
  },
  {
    id: "hall-wattens-culture-walk",
    name: "Hall old-town culture walk",
    promise: "A compact historic walk with sheltered stops and local food",
    region: "Tyrol",
    country: "Austria",
    kind: ["culture", "villages", "food", "accessible"],
    difficulty: "easy",
    latitude: 47.283,
    longitude: 11.507,
    travel: { walking: null, bicycle: 46, public: 24, car: 22, mixed: 26 },
    durationMinutes: 150,
    crowd: "moderate",
    crowdWindow: "13:30–16:30",
    confidence: "Medium",
    updated: "45 minutes ago",
    validation: "Data-based suggestion",
    imageTone: "culture",
    summary:
      "A short old-town circuit through arcades, small museums and independent food stops, suitable when mountain weather is unstable.",
    reasons: ["Weather-safe alternative", "Easy by public transport", "Accessible route options"],
    tradeoffs: ["Moderate rather than low crowd", "Urban rather than mountain setting"],
    comparison: {
      original: "Innsbruck old town",
      reachDifference: "+6 minutes travel",
      advantages: ["Lower crowd pressure", "Similar historic character", "More local businesses on the route"],
    },
    itinerary: [
      { time: "13:15", label: "Train from Innsbruck" },
      { time: "13:40", label: "Historic centre orientation" },
      { time: "14:20", label: "Covered arcade and museum option" },
      { time: "15:20", label: "Independent tasting stop" },
      { time: "16:00", label: "Return train" },
    ],
    mobility: ["24 minutes by train and short walk", "Step-free station route available", "No parking recommendation required"],
    localBenefit: "The itinerary directs spending toward independent businesses outside Innsbruck’s busiest visitor zone.",
    partner: "Pilot tasting reward proposed with a local producer.",
    safety: ["Mostly paved route", "Check museum opening times", "Rain-safe sections available"],
    points: 50,
    crowdByHour: [
      { time: "10:00", level: "moderate" },
      { time: "12:00", level: "high" },
      { time: "15:00", level: "moderate" },
      { time: "17:00", level: "low" },
    ],
  },
  {
    id: "bohinj-mostnica",
    name: "Mostnica gorge and Stara Fužina",
    promise: "Forest, water and a village route beyond the busiest lakefront",
    region: "Julian Alps",
    country: "Slovenia",
    kind: ["hiking", "nature", "water", "villages"],
    difficulty: "moderate",
    latitude: 46.307,
    longitude: 13.891,
    travel: { walking: null, bicycle: 39, public: 51, car: 26, mixed: 46 },
    durationMinutes: 210,
    crowd: "moderate",
    crowdWindow: "08:00–11:00",
    confidence: "Medium",
    updated: "1 hour ago",
    validation: "Locally reviewed",
    imageTone: "forest",
    summary:
      "A shaded gorge walk and village circuit that offers a comparable nature experience to the lakefront with better early-day distribution.",
    reasons: ["Strong nature match", "Recommended off-peak arrival", "Local village benefit"],
    tradeoffs: ["Moderate difficulty", "Some wet and uneven surfaces"],
    comparison: {
      original: "Lake Bohinj main shore",
      reachDifference: "+12 minutes travel",
      advantages: ["Lower early-morning crowd", "More varied route", "Supports village services"],
    },
    itinerary: [
      { time: "07:45", label: "Leave Bohinj accommodation" },
      { time: "08:10", label: "Start gorge trail" },
      { time: "09:30", label: "Turnaround viewpoint" },
      { time: "10:20", label: "Stara Fužina village stop" },
      { time: "11:15", label: "Return" },
    ],
    mobility: ["26 minutes by car", "Seasonal public-transport option", "Paid trail entry may apply"],
    localBenefit: "The route spreads visits from the lake shore toward a village with year-round services.",
    safety: ["Trail can be slippery", "Not suitable for strollers", "Avoid during flood warnings"],
    points: 65,
    crowdByHour: [
      { time: "08:00", level: "low" },
      { time: "10:00", level: "moderate" },
      { time: "12:00", level: "high" },
      { time: "16:00", level: "moderate" },
    ],
  },
  {
    id: "engadin-village-rail",
    name: "Lower Engadin village rail day",
    promise: "Car-free villages, short walks and a scenic rail connection",
    region: "Graubünden",
    country: "Switzerland",
    kind: ["villages", "culture", "nature", "accessible"],
    difficulty: "easy",
    latitude: 46.795,
    longitude: 10.299,
    travel: { walking: null, bicycle: 82, public: 48, car: 39, mixed: 50 },
    durationMinutes: 300,
    crowd: "low",
    crowdWindow: "09:30–15:30",
    confidence: "Low",
    updated: "2 hours ago",
    validation: "Data-based suggestion",
    imageTone: "village",
    summary:
      "A rail-based day connecting two small Engadin villages with optional short walks and local heritage stops.",
    reasons: ["Lower-impact mobility", "Flexible walking", "Low crowd estimate"],
    tradeoffs: ["Longer travel time", "Opening hours require confirmation"],
    comparison: {
      original: "St. Moritz centre",
      reachDifference: "+24 minutes travel",
      advantages: ["Lower predicted crowd", "Car-free itinerary", "Direct village spending"],
    },
    itinerary: [
      { time: "09:10", label: "Board regional train" },
      { time: "10:00", label: "First village walk" },
      { time: "12:15", label: "Local lunch option" },
      { time: "13:40", label: "Second village and heritage stop" },
      { time: "15:20", label: "Return train" },
    ],
    mobility: ["48 minutes by regional train", "Step-free itinerary requires confirmation", "No parking needed"],
    localBenefit: "The plan directs time and spending to smaller communities connected by existing rail capacity.",
    safety: ["Check seasonal path closures", "Mountain weather changes quickly", "Some heritage sites have limited hours"],
    points: 70,
    crowdByHour: [
      { time: "09:00", level: "low" },
      { time: "12:00", level: "low" },
      { time: "15:00", level: "low" },
      { time: "17:00", level: "moderate" },
    ],
  },
  {
    id: "vercors-winter-village",
    name: "Vercors winter village circuit",
    promise: "A low-pressure winter walk with indoor local stops",
    region: "French Alps",
    country: "France",
    kind: ["winter", "villages", "food", "family"],
    difficulty: "easy",
    latitude: 45.178,
    longitude: 5.721,
    travel: { walking: null, bicycle: null, public: 64, car: 34, mixed: 59 },
    durationMinutes: 180,
    crowd: "low",
    crowdWindow: "11:00–15:00",
    confidence: "Low",
    updated: "3 hours ago",
    validation: "Data-based suggestion",
    imageTone: "winter",
    summary:
      "A gentle winter village circuit with a marked snow path and optional indoor food stop, designed as an alternative to a crowded ski base.",
    reasons: ["Family-friendly", "Low crowd estimate", "Indoor fallback available"],
    tradeoffs: ["Snow conditions not live", "Public transport is infrequent"],
    comparison: {
      original: "Major resort base area",
      reachDifference: "+18 minutes travel",
      advantages: ["Lower crowd pressure", "Lower-cost activity", "Local village spend"],
    },
    itinerary: [
      { time: "10:30", label: "Leave accommodation" },
      { time: "11:05", label: "Begin marked village snow walk" },
      { time: "12:15", label: "Indoor local product stop" },
      { time: "13:10", label: "Short viewpoint loop" },
      { time: "14:15", label: "Return" },
    ],
    mobility: ["34 minutes by car", "Seasonal coach service", "Winter parking availability not confirmed"],
    localBenefit: "The circuit supports a village economy outside the main lift and accommodation concentration.",
    safety: ["Check snow and ice conditions", "Winter footwear required", "Route may close during severe weather"],
    points: 60,
    crowdByHour: [
      { time: "09:00", level: "moderate" },
      { time: "11:00", level: "low" },
      { time: "13:00", level: "low" },
      { time: "16:00", level: "moderate" },
    ],
  },
];

export const alpineRegions = [
  { name: "Valle d’Aosta", country: "Italy", pressure: "moderate", experiences: 1, x: 34, y: 61 },
  { name: "Allgäu", country: "Germany", pressure: "high", experiences: 1, x: 53, y: 31 },
  { name: "Tyrol", country: "Austria", pressure: "moderate", experiences: 1, x: 62, y: 39 },
  { name: "Graubünden", country: "Switzerland", pressure: "low", experiences: 1, x: 48, y: 51 },
  { name: "Julian Alps", country: "Slovenia", pressure: "moderate", experiences: 1, x: 78, y: 49 },
  { name: "French Alps", country: "France", pressure: "low", experiences: 1, x: 20, y: 67 },
] as const;
